gitops-runtime:
  global:
    codefresh:
      accountId: 6787f1c9dbf921df07817022
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
